import React from "react";

function Slidertext() {
  return (
    <div>
      <div className="m-scrolll">
        <div className="sliding-text">
          <div>
            <h1>
              {
                " N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK - N3WCR4FT WEB SITE - AEYES NFT'S - CELL PROJECT - BLOCKNOTE - WORDSMETA - NEWSLINK -  "
              }
            </h1>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Slidertext;
